coolsnowwolf/packages

sound/pulseaudio/Makefile

After this pr https://github.com/coolsnowwolf/lede/pull/2690 ，there will be a problem like this:
tmp/.config-package.in:84257:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:84257:   symbol PACKAGE_pulseaudio-profiles depends on PACKAGE_pulseaudio-profiles
tmp/.config-package.in:84273:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:84273:   symbol PACKAGE_pulseaudio-tools depends on PACKAGE_pulseaudio-tools

pulseaudio: fix recursive dependencies

---

utils/containerd/Makefile
utils/runc/Makefile

Maintainer: @G-M0N3Y-2503 (find it by checking history of the package Makefile)
Compile tested: x86_64, coolsnowwolf/lede@ee1ea5b1
Run tested: x86_64, coolsnowwolf/lede@ee1ea5b1
Description:
Fixes coolsnowwolf/lede#3222, fixes coolsnowwolf/lede#3282, fixes coolsnowwolf/lede#3213, fixes coolsnowwolf/lede#1759
由于`Build/InstallDev`删除了build_dir中编译好的bin文件而未删除stamp文件，二次编译时buildroot误认为编译过程不需要再次进行

Fix necessary recompiling not detected in runc/containerd

---

utils/containerd/Makefile
utils/docker-ce/Config.in
utils/libnetwork/Makefile
utils/runc/Makefile

fix pull request #56 from hyird/master
containerd: bump to 7ad184331fa3e55e52b890ea95e65ba581ae3429
libnetwork: bump to 9fd385be8302dbe1071a3ce124891893ff27f90f
runc: bump to dc9208a3303feef5b3839f4323d9beb36df0a9dd

docker-ce: fix build failure caused by depend missing

---

sound/forked-daapd/Makefile

This commit fixes: 
When the ttyd and forked-daapd are both selected, there will be some error messages appearing as follows.
`* check_data_file_clashes: Package libwebsockets-openssl wants to install file /home/runner/work/openwrt/openwrt/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/libwebsockets.so
But that file is already provided by package  * libwebsockets-full`

forked-daapd: fix compile error with ttyd

---

admin/netdata/Makefile

update netdata to 1.22.0
Description:

update netdata to 1.22.0

---

net/dnscrypt-proxy2/Makefile

Maintainer: DNSCrypt
Description:

update to v2.0.44

---

net/https-dns-proxy/Makefile

只要选了开机就会自启 添加dnsmasq转发。得默认关了
Luci 也是控制init.d enbale disable 默认关闭不影响

https-dns-proxy: do not boot on startup

---

multimedia/minidlna/patches/999-05-fix-setjmp-buffer-multiple-def.patch

minidlna: fix GCC 10 multiple def compilation error

---

.travis_do.sh

Target ar71xx is deprecated and removed in the master branch and makes SDK
not available anymore. Travis fails because of that.
It was superseded by target ath79. These devices have 4 MB flash and/or 32 MB RAM.
However, ath79 is being used by CircleCI if you have it configured for
your repository and if you are contributing to this repository. It
is not good to have two CI for the same target. Let's use powerpc.
Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>

Sync openwrt

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: Update to v2.2.8

---

net/zerotier/Makefile

This version finally fixes the "coma" bug that some users have experienced in 1.6.

Zerotier: update 1.6.4

---

net/haproxy/Makefile
net/haproxy/get-latest-patches.sh

haproxy: update v2.2.9

---

utils/docker-ce/Makefile

GO_PKG_BUILD_VARS should be put behind golang-package.mk,
otherwise it will be overridden.
Fixes: coolsnowwolf/lede#6477
Signed-off-by: Tianling Shen <cnsztl@immortalwrt.org>

docker-ce: fix vars order

---

devel/meson/Makefile
devel/meson/meson.mk

Maintainer: neheb 125f6ff9ec01c57e0cf57b042b95884f160cf48f
Compile tested: Newifi OpenWrt R21.2.1 
Description:
It should use python3 for pathlib

Use python3

---

libs/xr_usb_serial_common/Makefile
libs/xr_usb_serial_common/patches/0001-common.c-fix-kernel-5.10-builds-with-CONFIG_PM-enabl.patch

Description:
fix the error corresponding to https://github.com/openwrt/packages/commit/69cf7836df9e226b4d596d057ca6ad846201e0d0,
xr_usb_serial_common.c:1574:15: error: 'ASYNCB_INITIALIZED' undeclared
(first use in this function); did you mean 'RCU_INITIALIZER'?
Use tty_port_initialized in order to determine the status of the TTY
port. This is compatible with Kernel 5.10 and at least Kernel 5.4.

try to fix #issue-909935861

---

net/acme/Makefile

acme:update to 2.9.0

---

lang/python/python3-speedtest-cli/Makefile

Description:
to support python 3.10

python3-speedtest-cli: update to version 2.1.3

---

net/privoxy/files/privoxy.config

Description:
Privoxy: add missing option

Privoxy: add missing option

---

net/zerotier/Makefile

zerotier: bump to v1.6.6

---

libs/nss/Makefile

Fix the compilation problem of the ubuntu -21.10
Description:

 libs/nss：update to 3.69

---

utils/docker-compose/Makefile

What's Changed:
- Return an error when failing to list containers by @ulyssessouza
- compose logs to notify printer about container lifecycle events by
@ndeloof
- Turn external volume usage into a warning instead of erroring by
@ulyssessouza
- Use filepath instead of path to check if the dockerfile path is
abolute or not by @glours
- Upgrade version of opencontainers/image-spec (security issue) by
@glours
- Merge and fix Convert function from docker/compose-switch by
@ulyssessouza
- Fix to use Key instead of Service for graph updates by @Mygao
- Fix links resolution by @ulyssessouza
- Don't check compose labels on external volumes by @ndeloof
- Refactoring variable name by @ulyssessouza
- Add multiargs build e2e tests by @ulyssessouza

docker-compose: Update to version 2.2.2

---

net/aria2/files/aria2.init

Description:
Aria2 session (downloading status) would loss every time aria2 service (re)starts, e.g. mannually restart aria2 service or after device reboot. 
Related issue: coolsnowwolf/lede#5829
This problem is caused by unconditionally file creation of `$session_file` by `_create_file()` in function `aria2_start()`.
In this PR, the existence of `$session_file` is checked before creating a new one. Further, if `$session_file` exists, check read&write permission of it.

Fix aria2 session lost issue

---

net/aria2/files/aria2.init

Description:
Fix syntax error of PR #349. Further, the existence of directory `$config_dir` is checked before creation.

fix syntax error and funcion enhancement

---

net/verysync/Makefile

x86_64
Description:
2.10.4已经被删除，因此更新到最新

update verysync to newest

---

libs/rblibtorrent/Makefile
net/qBittorrent/Makefile

Description: 改用cmake构建，测试 arm64 及 x86 都正常。

Update qBittorrent v4.4.1及相关依赖库并改用cmake构建

---

libs/qtbase/Makefile
libs/qtbase/patches/010-gcc11.patch
libs/qttools/Makefile
libs/rblibtorrent/Makefile

Run tested: (GCC 11 arm64 works )
Description: rblibtorrent: bump to git HEAD & Fix installation file missing symlinks
qtbase & qttools update to 5.15.3

rblibtorrent: bump to git HEAD

---

lang/golang/golang/Makefile

Includes fix for [CVE-2022-24921](https://github.com/advisories/GHSA-6685-ffxp-xm6f) (regexp: stack overflow (process exit)
handling deeply nested regexp).
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

golang: Update to 1.17.8

---

net/openssh/Makefile
net/openssh/patches/010-32bit-seccomp.patch
net/openssh/patches/020-improve-detection-of-fzero-call-used-regs.patch

Maintainer: @tripolar
Compile tested: aarch64, Turris MOX, OpenWrt master
Run tested: aarch64, Turris MOX, OpenWrt master
Description: According to reports from other distributions, using openssh server 8.9p1 on 32bit architectures without 32bit-seccomp.patch (which is already upstream in the 8.9 maintenance branch) does not accept connections. I didn't test this if OpenWrt is affected by this bug yet.

openssh: update to 8.9p1

---

libs/expat/Makefile

add CMAKE_HOST_OPTIONS back to fix host-build errors.

expat: add CMAKE_HOST_OPTIONS

---

admin/netdata/Makefile

fix:
Package netdata is missing dependencies for the following libraries:
liblz4.so.1

netdata: add liblz4 deps

---

net/qBittorrent/Makefile

v4.4.2 changelog:
FEATURE: Allow to limit max memory working set size (glassez)
BUGFIX: Fix UI crash when torrent is in a non-existent category (Kevin Cox)
BUGFIX: Correctly handle changing of global save paths (glassez)
BUGFIX: Disable performance alert (Chocobo1)
BUGFIX: Prevent loading resume data with inconsistent ID (glassez)
BUGFIX: Properly handle metadata download for an existing torrent (glassez)
BUGFIX: Prevent crash when open torrent destination folder (glassez)
WINDOWS: NSIS: Update Spanish, Spanish International and French translations(Juanjo Jiménez, RqndomHax)

qBittorrent: update to 4.4.2

---

libs/gnutls/Makefile
libs/gnutls/patches/010-m4.patch
libs/gnutls/patches/020-dont-install-m4-files.patch

Bump to latest upstream release. Rebased existing patches.
Signed-off-by: John Audia [graysky@archlinux.us](mailto:graysky@archlinux.us)

gnutls: Update to 3.7.4

---

libs/gnutls/Makefile

Fixes:
Package libgnutls is missing dependencies for the following libraries:
libz.so.1
Disable zlib support to avoid that.
Signed-off-by: John Audia <graysky@archlinux.us>
[disable zlib and zstd]
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>

gnutls: disable zlib

---

net/nlbwmon/files/nlbwmon.config

nlbwmon: netlink_buffer_size 16777216

---

net/miniupnpd/Makefile

Maintainer: me 
Compile tested: lede tag *[20211107](https://github.com/geniusjoe/lede/releases/tag/20211107)*
Run tested: self menual test.
Description:
在使用 lede 拉取 feed 后，执行 `make download` 下载 `miniupnpd` 包时，会出现 curl 下载进度到 100% 后卡住的现象。
```
curl -f --connect-timeout 20 --retry 5 --location --insecure http://miniupnp.free.fr/files/miniupnpd-2.0.20170421.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 1010k    0 1010k    0     0    207      0 --:--:--  1:23:13 --:--:-- 
```
排查原因后发现是 `miniupnpd` 镜像在下载时，实际上下载的是 `.tar` 后缀，而非 `.tar.gz` 后缀的包。目前这个问题已经被 `miniupnpd` 修复，但是在使用浏览器在 [镜像仓库网站](http://miniupnp.free.fr/files) 手动下载 [该文件](http://miniupnp.free.fr/files/download.php?file=miniupnpd-2.0.20170421.tar.gz) …

miniupnpd: change download repo url

---

utils/dockerd/Makefile

This release of Docker Engine comes with updated versions of the `compose`,
`buildx`, `containerd`, and `runc `components, as well as some minor bugfixes.
Use a RWMutex for stateCounter to prevent potential locking congestion https://github.com/moby/moby/pull/43426.
Prevent an issue where the daemon was unable to find an available IP-range in
some conditions https://github.com/moby/moby/pull/43360
Update Docker Compose to [v2.5.0](https://github.com/docker/compose/releases/tag/v2.5.0).
Update Docker Buildx to [v0.8.2](https://github.com/docker/buildx/releases/tag/v0.8.2).
Update Go runtime to [1.17.9](https://go.dev/doc/devel/release#go1.17.minor).
Update containerd (containerd.io package) to [v1.6.4](https://github.com/containerd/containerd/releases/tag/v1.6.3).
Update runc version to …

dockerd: update to v20.10.15

---

net/qBittorrent/Makefile

Tue May 24 2022 - sledgehammer999 <sledgehammer999@qbittorrent.org> - v4.4.3.1
- BUGFIX: Fix broken translations (sledgehammer999)
Sun May 22 2022 - sledgehammer999 <sledgehammer999@qbittorrent.org> - v4.4.3
- BUGFIX: Correctly handle changing of temp save path (glassez)
- BUGFIX: Fix storage in SQLite (glassez)
- BUGFIX: Correctly apply content layout when "Skip hash check" is enabled (glassez)
- BUGFIX: Don't corrupt IDs of v2 torrents (glassez)
- BUGFIX: Reduce the number of hashing threads by default (improves hashing speed on HDDs) (summer)
- BUGFIX: Prevent the "update dialog" from blocking input on other windows (summer)
- BUGFIX: Add trackers in exported .torrent files (glassez)
- BUGFIX: Fix wrong GUI behavior in "Optional IP address to bind to" setting (Chocobo1)
- WEBUI: Fix …

qBittorrent: update to 4.4.3.1

---

multimedia/aliyundrive-webdav/Makefile

Ref: https://github.com/messense/aliyundrive-webdav/commit/876ff07fce522d6740cbd1b7270300f3eabb7b45#diff-cdd8d0dd68af9ae117bdd8a83edf3c987975b438264ca05ab40ffc1970bbe399
Description:

aliyundrive-webdav: update to 1.5.1

---

lang/ruby/patches/001-fix-build-with-libressl-3.5.patch
lang/ruby/patches/002-fix-operator-precedence.patch

fix: https://github.com/coolsnowwolf/lede/issues/9838

ruby: fix build with LibreSSL over v3.5

---

utils/tar/Makefile

fixes compilation when deselecting options.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

tar: add PKG_CONFIG_DEPENDS

---

multimedia/ffmpeg/Makefile
multimedia/ffmpeg/patches/050-glibc.patch

Bump to latest upstream version, manually rebased: 050-glibc.patch
Tested using:
ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=30 testsrc.mpg
Resulting mpg was good.
Build system: x86_64
Build-tested: bcm2711/RPi4B
Run-tested: bcm2711/RPi4B
Signed-off-by: John Audia <therealgraysky@proton.me>

ffmpeg: update to 5.1

---

utils/docker-compose/Makefile

What's Changed:
- Enhancements:
- add support of environment secret during build step by @glours
- Fixes:
- networks: prevent issues due to duplicate names by @milas
- Use appropriate dependency condition for one-shot containers when
running compose up --wait by @laurazard
- Fix environment variable expansion by @ulyssessouza in
compose-spec/compose-go#276
- Validate depended-on services exist in consistency check by
@laurazard in compose-spec/compose-go#281
- Fix hash usage in environment values by @ulyssessouza in
compose-spec/compose-go#283
- build: respect dependency order for classic builder by @milas
- fix: panic caused by empty string argument by @nicksieger
- (re)start should not impact one-off containers by @ndeloof
- Fix issue with close networks name on up and down command by …

docker-compose: Update to version 2.7.0

---

net/softethervpn5/patches/150_remove-restriction.patch
net/softethervpn5/patches/151-fix-openvpn-static-route-push.patch

Compile tested: x86_64
Run tested: tested on N5105 x64
Description:
Cherry picked a patch for fixing softether openvpn protocol can't correctly push static routes.
Also fixed patch file line ending issue.

fix softether openvpn static route push issue

---

net/qBittorrent/Makefile

Mon Aug 22 2022 - sledgehammer999 <sledgehammer999@qbittorrent.org> - v4.4.4
- BUGFIX: Correctly handle data decompression with Qt 6.3 (brvphoenix)
- BUGFIX: Fix wrong file names displayed in tooltip (Chocobo1)
- BUGFIX: Fix incorrect "max outgoing port" setting (glassez)
- BUGFIX: Make working set limit available only on libtorrent 2.0.x builds (summer)
- BUGFIX: Try to recover missing tags (summer)
- RSS: Clear RSS parsing error after use (glassez)
- WEBAPI: Set HTTP method restriction on WebAPI actions (Chocobo1)
- WINDOWS: Work around application stuttering on Windows (Chocobo1)
- WINDOWS: NSIS: Update Portuguese, Italian, Korean, Latvian translations(Blackspirits, bovirus, Minseo Lee, Coool)
- LINUX: Improve D-Bus notifications handling (glassez)
- MACOS: Open destination folders on …

qBittorrent: update to 4.4.4

---

net/webdav-hacdias/Makefile
net/webdav-hacdias/files/webdav.config
net/webdav-hacdias/files/webdav.init
net/webdav-hacdias/files/webdav.yaml

来源：https://github.com/hacdias/webdav
相比原版只修改了一处造成固件备份配置文件时会错误的备份整个系统，其余未修改。
简单的webdav共享，配合luci那边的提交，简单的配置文件。
长达1个月的测试，至少在视频文件分享方面没啥问题，配置文件说明见来源页，支持多用户，支持自定义端口。
不要使用网页直接打开，这样只会显示网页源代码。
默认不走https，win10可能需要启用不安全项并通过添加一个网络位置使用，电视盒子啥的直接用没啥问题。
可能由于文件系统或缓存原因传输文件时不会实时更新进度条。
测试主要使用电视kodi播放超大体积蓝光原盘（比如高达100+GB的单文件视频）
kodi使用webdav协议时会默认启用缓存。
可能不具备太多的安全性，开放外网请走加密。

add webdav

---

libs/libssh2/Makefile

Release Notes:
https://www.libssh2.org/changes.html
Signed-off-by: Nick Hainke <vincent@systemli.org>

libssh2: update to 1.10.0

---

libs/libpam/Makefile

Release Notes:
https://github.com/linux-pam/linux-pam/releases/tag/v1.5.2
Install the pkgconfig files for provided libraries.
Signed-off-by: Nick Hainke <vincent@systemli.org>

libpam: update to 1.5.2

---

libs/libssh/Makefile

Release Notes:
https://www.libssh.org/2022/08/26/libssh-0-10-0/
Signed-off-by: Nick Hainke <vincent@systemli.org>

libssh: update to 0.10.2

---

libs/gnutls/Makefile

- libgnutls: Fixed double free during verification of pkcs7 signatures.
Reported by Jaak Ristioja (#1383). [GNUTLS-SA-2022-07-07, CVSS: medium]
[CVE-2022-2509]
- libgnutls: gnutls_hkdf_expand now only accepts LENGTH argument less than or
equal to 255 times hash digest size, to comply with RFC 5869 2.3.
- libgnutls: Length limit for TLS PSK usernames has been increased
from 128 to 65535 characters (#1323).
- libgnutls: AES-GCM encryption function now limits plaintext
length to 2^39-256 bits, according to SP800-38D 5.2.1.1.
- libgnutls: New block cipher functions have been added to transparently
handle padding.  gnutls_cipher_encrypt3 and gnutls_cipher_decrypt3 can be
used in combination of GNUTLS_CIPHER_PADDING_PKCS7 flag to automatically
add/remove padding if the length of the original …

gnutls: update to 3.7.7

---

utils/dockerd/Makefile

This release of Docker Engine comes with a fix for a low-severity security issue,
some minor bug fixes, and updated versions of Docker Compose, Docker Buildx,
containerd, and runc.
Client
Add Bash completion for Docker Compose https://github.com/docker/cli/pull/3752.
Builder
Fix an issue where file-capabilities were not preserved during build https://github.com/moby/moby/pull/43876.
Fix an issue that could result in a panic caused by a concurrent map read and map write https://github.com/moby/moby/pull/44067
Daemon
Fix a security vulnerability relating to supplementary group permissions, which
could allow a container process to bypass primary group restrictions within the
container [CVE-2022-36109](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-36109), …

dockerd: Update to v20.10.18

---

net/smartdns/Makefile

Description:  https://github.com/openwrt/packages/commit/c4ef81e8293c1dfc530b49102adfb6c381e11916

smartdns: bump to 1.2022.38

---

libs/qttools/Makefile

2022-10-02T05:58:42.0628939Z 
2022-10-02T05:58:42.0630827Z 10/02 05:58:42 [[1;32mNOTICE[0m] CUID#7 - Redirecting to https://download.qt.io/official_releases/qt/5.15/5.15.4/submodules/qttools-everywhere-opensource-src-5.15.4.tar.xz
2022-10-02T05:58:42.4746198Z 
2022-10-02T05:58:42.4747473Z 10/02 05:58:42 [[1;32mNOTICE[0m] Download complete: /home/runner/work/OpenWrt_Build/OpenWrt_Build/openwrt/tmp/aria2c/qttools-everywhere-opensource-src-5.15.4.tar.xz_CofVxWQbOE
2022-10-02T05:58:42.7582351Z [#12ca03 720KiB/8.4MiB(8%) CN:8 DL:9.9MiB]
2022-10-02T05:58:43.7618575Z [#12ca03 6.5MiB/8.4MiB(77%) CN:3 DL:6.1MiB]
2022-10-02T05:58:44.7773775Z [#12ca03 7.9MiB/8.4MiB(93%) CN:2 DL:3.8MiB]
2022-10-02T05:58:45.1921399Z 
2022-10-02T05:58:45.1922834Z 10/02 05:58:45 [[1;32mNOTICE[0m] Download …

qttools: remove the url that caused the downloads to fail

---

libs/libxml2/Makefile

This fixes:
- CVE-2022-2309
Release Notes:
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.0
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.1
- https://gitlab.gnome.org/GNOME/libxml2/-/releases/v2.10.2
Also drop removed docbook compile switch.
Disable PKG_FIXUP to allow backporting.
Signed-off-by: Nick Hainke <vincent@systemli.org>
Signed-off-by: Michael Heimpold <mhei@heimpold.de>

libxml2: update to 2.10.2

---

net/uugamebooster/Makefile

Maintainer: me / @<github-user> (find it by checking history of the package Makefile)
aarch64_cortex-a53
aarch64, QSDK, OpenWrt R22.8.22, testing passed
Description:
uugamebooster bump to v3.0.4

uugamebooster bump to v3.0.4

---

admin/nload/Makefile

Signed-off-by: Jacky Guo [leickwell@hotmail.com](mailto:leickwell@hotmail.com)
Maintainer: me
Compile tested: aarch64/mt7622), ramips/mt7628
Run tested: Redmi AX6S, Minew G1-C
Description:
A console application which monitors network
traffic and bandwidth usage in real time.
https://github.com/rolandriegel/nload

nload: add new package

---

libs/libesmtp/Makefile

Fix WARNING: Makefile 'package/feeds/packages/libesmtp/Makefile' has a build dependency on 'meson/host', which does not exist

libesmtp: Compile with tools/meson

---

multimedia/ffmpeg/Makefile

The previous solution overwrote the provide from ``define Package/libffmpeg/Default``, but that's not what was wanted. Thus libffmpeg-full should provide three packages libffmpeg, libffmpeg-mini and libffmpeg-audio-dec
Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>

ffmpeg: libffmpeg-full package should provide libffmpeg package, too

---

utils/docker-compose/Makefile

docker-compose: update to v2.12.2

---

libs/sqlite3/Config-lib.in
libs/sqlite3/Makefile

1. Added a new option for SQLITE3_COLUMN_METADATA.
2. Minor cleanup Makefile and fixed 2 typo errors.
Fixes: CVE-2022-35737
Signed-off-by: Tianling Shen <cnsztl@immortalwrt.org>

sqlite3: Update to 3.40.0

---

net/uugamebooster/Makefile

Maintainer: me / @ (find it by checking history of the package Makefile)
x86_64
aarch64, QSDK, OpenWrt R22.11.16, testing passed
Description:
uugamebooster bump to v3.3.2

uugamebooster bump to v3.3.2

---

net/iperf3/Makefile

Fix iperf-ssl No file libiperf.so.* as it used "--disable-shared"

Fix iperf-ssl No file libiperf.so.* 

---

net/uugamebooster/Makefile

Maintainer: me
aarch64_cortex-a53, Qihoo 360 V6, r5607-c267a13ce SNAPSHOT
ARMv8, GL-AX1800 IPQ6018/AP-CP03-C1, OpenWrt R22.12.1, testing passed
Description:
uugamebooster bump to v3.6.2

uugamebooster bump to v3.6.2

---

lang/php7/Makefile

Since the OpenWrt's stub libiconv implementation is now gone, we can build against musl's internal one or the external libiconv implementation.
This needs minor adjustements in the makefile to allow PHPs build to choose the right path when cross-compiling.
Fixes: https://github.com/coolsnowwolf/lede/issues/10805
Signed-off-by: Michael Heimpold <mhei@heimpold.de>

php7: fixup libiconv usage

---

net/rclone/Makefile

```shell
$ curl https://goproxy.baidu.com
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
The ssl certificate of domain `goproxy.baidu.com` has expired.
This commit delete `GOPROXY` here, so that it can be customized before compilation.

rclone: remove GOPROXY env var

---

net/pgyvpn/files/etc/init.d/pgyvpn

Maintainer: @aiamadeus
Compile tested: x86-64 ImmortalWrt SNAPSHOT 
Run tested: x86-64 ImmortalWrt SNAPSHOT 
Description:
Running vncinit script should use `-C` instead of `-n`

pgyvpn: Fix vncinit parameter error (use `-C`)

---

libs/boost/Makefile

Boost has moved downloads to JFrog Artifactory
https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html

boost: fix unavailable source

---

net/tailscale/Makefile

Fix “tailscaled.state” file does not exist；Remove redundant '/'；
Description:
Fix “tailscaled.state” file does not exist；Remove redundant '/'；

“tailscaled.state” file does not exist

---

net/aria2/files/aria2.init

Maintainer: @coolsnowwolf 
Compile tested: x86 aarch64
Run tested: x86,OpenWRT R23.5.1
Description:
aira2 下载 https网站的文件的时候会发生‘SSL/TLS handshake failure: unable to get local issuer certificate’这个问题，查证后发现是没有加载正确的ca-certificate导致的，在x86和arm64中测试过了，可以解决这个问题;
同时可能要将ca-certificate设置成aria2的依赖

aria2:fix ssl errors

---

utils/zoneinfo/Makefile

Maintainer: Michael Geddes
Compile tested: x86_64 generic, gcc 13 on Arch Linux WSL 2
Run tested: TBD
Description:
Should fix: https://github.com/coolsnowwolf/lede/issues/11199

zoneinfo: updated to the latest release

---

net/tailscale/Makefile

Maintainer: Max Bian (picmax@gmail.com)
Compile tested: X86_64 on QEMU, OpenWrt R23.5.1
Run tested: Compiled, installed, and ran well.
Description:

Bump Tailscale to 1.42.0 from 1.36.0

---

net/smartdns/Makefile

Tab was converted into spaces when the code was pasted, causing compile failures. Fixing it.

Fixing the unwanted tab->space conversion

---

admin/htop/Makefile

Maintainer: Etienne CHAMPETIER <champetier.etienne@gmail.com>
Compile tested: 
```
make package/feeds/packages/htop/compile V=s                 
make[2]: Entering directory '/home/evine/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/evine/lede/scripts/config'
make[1]: Entering directory '/home/evine/lede'
make[2]: Entering directory '/home/evine/lede/package/libs/ncurses'
make[2]: Leaving directory '/home/evine/lede/package/libs/ncurses'
time: package/libs/ncurses/host-compile#0.11#0.03#0.13
make[2]: Entering directory '/home/evine/lede/package/libs/toolchain'
echo "libc" >> /home/evine/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/evine/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.instal …
```

htop: enable unicode.

---

net/mosdns/patches/100-update-deps.patch
net/mosdns/patches/101-fix-nftset-mask.patch
net/mosdns/patches/200-add-debug-log-again.patch

Maintainer: Tianling Shen <cnsztl@immortalwrt.org>
Compile tested: 
```
evine@opbuilder  ~/lede   master  make package/feeds/packages/mosdns/{clean,compile} V=s 
Collecting package info: done
make[2]: Entering directory '/home/evine/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/evine/lede/scripts/config'
make[1]: Entering directory '/home/evine/lede'
make[2]: Entering directory '/home/evine/lede/feeds/packages/net/mosdns'
rm -rf /home/evine/lede/build_dir/target-x86_64_musl/mosdns-5.1.3
/home/evine/lede/scripts/ipkg-remove mosdns /home/evine/lede/bin/packages/x86_64/packages/mosdns_5.1.3-1_x86_64.ipk
removed '/home/evine/lede/bin/packages/x86_64/packages/mosdns_5.1.3-1_x86_64.ipk'
rm -f …
```

mosdns: sync with upstream

---

net/zerotier/Makefile
net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-paths.patch
net/zerotier/patches/0002-remove-PIE-options.patch
net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch
net/zerotier/patches/0004-add-missing-libatomic.patch
net/zerotier/patches/0005-remove-noexecstack.patch

* split up "fix makefile" patch logical distinct parts
* add libatomic dependency needed for prometheus-cpp-lite-1.0
* refresh patch series
* improve warning message in init script
Signed-off-by: Moritz Warning <moritzwarning@web.de>

zerotier: update to 1.12.1

---

utils/zstd/Makefile

Fix zstd: Compilation failure caused by format misalignment issues

---

utils/dockerd/Config.in

上次的 pr #723 将一部分非必要的模块默认启用了，这个 pr 是恢复原来默认的配置值

docker: revert kernel modules support to default

---

admin/btop/Makefile

fix `btop` compilation with musl 1.2.4
Reference: https://github.com/openwrt/packages/pull/21048

btop: fix compilation with musl 1.2.4

---

lang/perl/Makefile

fix `perl` compilation with musl 1.2.4
Reference: https://github.com/openwrt/packages/pull/21069

perl: fix compilation with musl 1.2.4

---

utils/btrfs-progs/Makefile

Fix `btrfs-progs` compilation with musl 1.2.4

btrfs-progs: fix compilation with musl 1.2.4

---

multimedia/xupnpd/Makefile

xupnpd: fix compilation with musl 1.2.4

---

multimedia/aliyundrive-webdav/Makefile

fix aliyundrive-webdav compile issues
```log
install: cannot stat '/home/arrio/lede/build_dir/target-aarch64_cortex-a53_musl/aliyundrive-webdav-2.3.2/target/aarch64-unknown-linux-musl/stripped/aliyundrive-webdav': No such file or directory
```
https://github.com/coolsnowwolf/lede/issues/11800

fix: aliyundrive-webdav compile issues

---

net/strongswan/Makefile

DEPENDS 相比openwrt官方缺少一项 strongswan-libtls 会导致strongswan编译错误，增加后编译错误消失
Description:

Update strongswan Makefile

---

utils/docker/Makefile
utils/dockerd/Makefile

Update Docker to 26.1.1
Compile tested: CncTion J4125-4L Intel(R) Celeron(R) J4125 CPU,OpenWrt R24.5.1 LuCI Master (git-24.126.79400-c7873ae)
Run tested: CncTion J4125-4L Intel(R) Celeron(R) J4125 CPU,OpenWrt R24.5.1 LuCI Master (git-24.126.79400-c7873ae)
Description: Docker 26.1.0 still encounters the problem of "superfluous response.WriteHeader" error logs，Update docker version to 26.1.1 try to fix it .
See https://github.com/moby/moby/issues/47448 https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5438 for more info.

docker: update to 26.1.1

---

net/speedtest-go/Makefile

Maintainer: TeleostNaCl [teleostnacl@gmail.com](mailto:teleostnacl@gmail.com)
Compile tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.096.15376-b029f06)
Run tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.096.15376-b029f06)
Description: Synchronize upstream updates: https://github.com/showwin/speedtest-go

speedtest-go: update to 1.7.5

---

net/speedtest-go/Makefile

Maintainer: TeleostNaCl [teleostnacl@gmail.com](mailto:teleostnacl@gmail.com)
Compile tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.130.56871-0191870)
Run tested: MediaTek Ralink MIPS MT7621 based boards Phicomm K2P Powered by LuCI Master (git-24.130.56871-0191870)
Description: Synchronize upstream updates: https://github.com/showwin/speedtest-go

speedtest-go: update to 1.7.7

---

net/uugamebooster/Makefile

Description:
uugamebooster bump to v4.14.4

uugamebooster: bump to v4.14.4

---

net/iperf3/Makefile

iperf3: update to 3.17.1

---

utils/zstd/Makefile

zstd: update to 1.5.6

---

net/nginx-util/Makefile
net/nginx-util/src/ubus-cxx.hpp

Maintainer: Peter Stadler
Compile tested: armv7, PHICOMM K3, master (85df79d)
Run tested: armv7, PHICOMM K3, master (85df79d), passed
Description:
https://github.com/coolsnowwolf/lede/pull/12212 requires GCC 13.3, which would report an error on nginx-util.
The upstream has fixed it in https://github.com/openwrt/packages/commit/d71e28de375edc17ae0e0c6f735a870759c9a3e8.

nginx-util: fix compilation with GCC13

---

net/softethervpn5/Makefile

Softethervpn 5.02.5180 has problems with IPv6 listening, updating to 5.02.5185 solves this issue.
Maintainer: @hellcatjack
Compile tested: x86-64 OpenWrt R24.7.7
Run tested: x86-64 OpenWrt R24.7.7 IPv4&v6 listening works
Description:
Softethervpn 5.02.5180 has problems with IPv6 listening cdaad87dd6b0f5809932fd24762795204dd1e501 , updating to 5.02.5185 solves this issue.

Softethervpn5: Fix IPv6 listening by updating to version 5.02.5185

---

net/tailscale/Makefile

已在 Lean's LEDE 最新 https://github.com/coolsnowwolf/lede/commit/062d85f8fd82ec53d4a505256583b3bdd19775fe 中成功使用 tailscale，编译无明显 error，运行无异常，请求合并
tailscale.com/admin/machines: 1.70.0-1 (OpenWrt)Linux 6.1.100 Connected

Update tailscale to 1.70.0

---

net/zerotier/Makefile
net/zerotier/patches/0002-remove-PIE-options.patch
net/zerotier/patches/0005-remove-noexecstack.patch

Compile tested: Nanopi-R2S R5C
Run tested: Nanopi R5C

zerotier: bump to 1.14.1

---

utils/tini/patches/002-Support-POSIX-basename-from-musl-libc.patch

Support POSIX basename used in musl libc 1.2.5.
This fixes compilation with musl libc 1.2.5.
build_dir/target-mips_24kc_musl/tini-0.19.0/src/tini.c:227:36: error: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
227 |         fprintf(file, "%s (%s)\n", basename(name), TINI_VERSION_STRING);
build_dir/target-mips_24kc_musl/tini-0.19.0/src/tini.c:227:25: error: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Werror=format=]
227 |         fprintf(file, "%s (%s)\n", basename(name), TINI_VERSION_STRING);
|                        ~^          ~~~~~~~~~~~~~~
|                         |          |
|                         char *     int
|                        %d

 tini: Fix compilation with musl libc 1.2.5

---

net/speedtest-go/Makefile

Update speedtest-go version to 1.7.9
Maintainer: TeleostNaCl [teleostnacl@gmail.com](mailto:teleostnacl@gmail.com)
Compile tested: MediaTek Ralink MIPS MT7621 based boards ZTE E8820S OpenWrt SNAPSHOT r28146+1-52b6c92479 / LuCI Master 24.326.01848
Run tested: MediaTek Ralink MIPS MT7621 based boards ZTE E8820S OpenWrt SNAPSHOT r28146+1-52b6c92479 / LuCI Master 24.326.01848
Description: Update speedtest-go package, a CLI with go to test internet speed

speedtest-go: update to 1.7.9

---

net/cloudflared/Makefile

Description:
[Test Build](https://github.com/Internet1235/gh-action-sdk/actions/runs/12733246621)

cloudflared: Update to 2024.12.2

---

net/iperf/Makefile
net/iperf/patches/020-fix-udp-checksum.patch

Description:
**[Test Build](https://github.com/Internet1235/gh-action-sdk/actions/runs/12723912568)**

iperf: bump to 2.2.1

---

utils/lrzsz/Makefile
utils/lrzsz/patches/300-neutralize-autofoo.patch

fix lrzsz build issues
https://github.com/coolsnowwolf/lede/issues/11409

lrzsz: merge upstream

---

net/nfs-kernel-server/Makefile
net/nfs-kernel-server/files/nfsd.init

…LEGACY_CLIENT_TRACKING option, and in kernel 6.12, if CONFIG_NFSD_LEGACY_CLIENT_TRACKING is still enabled, the following kernel panic may occur:
[   65.168486] ------------[ cut here ]------------
[   65.173115] kernel BUG at fs/nfsd/nfs4recover.c:534!
[   65.178085] Internal error: Oops - BUG: 00000000f2000800 [#1] SMP
[   65.184178] Modules linked in: fast_classifier shortcut_fe_cm sch_pie ath9k ath9k_common rtw88_8822cu rtw88_8822c rtw88_8822bu rtw88_8822b rtw88_8821cu rtw88_8821c rtl8192cu rtl8192c_common rtl_usb rt2800usb rt2800lib rt2500usb pppoe ppp_async mt7921u mt7921e mt7921_common mt76x0u mt76x0_common l2tp_ppp iwlmvm iwldvm carl9170 ath9k_hw ath5k ath11k_pci ath11k ath10k_pci ath10k_core ath snd_usb_audio rtw88_usb rtw88_core rtlwifi rt2x00usb rt2x00lib rsi_usb rsi_91x …

nfs-utils: enable nfsdcld

---

libs/libgpiod/Makefile
net/openssh/Makefile
net/openssh/patches/0001-build-construct_utmp-when-USE_BTMP-is-set.patch

Run tested: (aarch64, phicomm N1, tests done)
```
root@OP_N1:~# sshd -version
sshd: unrecognized option: v
OpenSSH_9.9p1, OpenSSL 3.0.15 3 Sep 2024
usage: sshd [-46DdeGiqTtV] [-C connection_spec] [-c host_cert_file]
[-E log_file] [-f config_file] [-g login_grace_time]
[-h host_key_file] [-o option] [-p port] [-u len]
root@OP_N1:~# 
```

openssh: update to 9.9p1

---

net/softethervpn5/patches/120-remove-region-restriction.patch

移除softethervpn5中针对China/Japan地区的企业功能限制
Maintainer: @parkycai 
Compile tested: x86_64
Run tested: x86_64
Description:
已测试通过

softethervpn5 remove region restriction

---

net/uugamebooster/Makefile

uu加速器的插件官方已升级至8.6.4版本。
另外，官方提供的可执行文件多了一个`xtables-nft-multi`，我不太了解如果直接新增依赖`iptables-nft`是否会产生其他影响，所以一并放在了`/usr/bin/`下。
如果处理方式不对敬请指教。
编译后的新包已安装在我的X86 OPENWRT上并且运行良好。

uugamebooster: upgrade to 8.6.4

---

net/nft-qos/files/lib/monitor.sh

nft-qos: fix monitor duplicates

---

utils/docker-compose/Makefile

Release notes:
https://github.com/docker/compose/releases/tag/v2.38.2
Description:

docker-compose: Update to version 2.38.2

---

net/uugamebooster/Makefile
net/uugamebooster/update.sh

uugamebooster: Bump to 9.6.12 and fix download link
