coolsnowwolf/packages

- utils/bandwidthd/Makefile
bandwidthd is very old ,compile it need extra CFLAGS.
> old code need extra CFLAGS

- multimedia/minidlna/patches/010-libav-fix.patch
> minidlna: fix dsd support

- net/keepalived/Config.in
- net/keepalived/Makefile
- net/keepalived/files/keepalived.config
- net/keepalived/files/keepalived.init
之前版本太老无法顺利编译，同步了官方19.07-rc2 的版本
使用默认配置编译成功。
> packages: sync with 19.07-rc2

- libs/libuhttpd/Makefile
fix issue https://github.com/coolsnowwolf/lede/issues/2953
> libuhttpd: update to 3.0.1

- net/shadowsocks-libev/Makefile
**shadowsocks-libev:rm shadowsocks-libev-config**
> shadowsocks-libev:rm shadowsocks-libev-config

- utils/squashfs-tools/patches/0005-mksquashfs-unsquashfs-fix-compilation-with-glibc-2.2.patch
跟 https://github.com/coolsnowwolf/lede/pull/2902 一起
fix issue https://github.com/coolsnowwolf/lede/issues/2895
> squashfs-tools: fix build error

- admin/netdata/Makefile
> netdata: update to version 1.19.0

- admin/netdata/Makefile
> netdata: update to version 1.20.0

- net/autossh/Makefile
- net/autossh/files/autossh.config
- net/autossh/files/autossh.init
* Sync source code from openwrt-snapshots
* Bump version to v1.4g
* Fix autostart error
> autossh: Sync source code from openwrt-snapshots and fix autostart error

- libs/hwloc/Makefile
- libs/libpciaccess/Makefile
- net/aircrack-ng/Config.in
- net/aircrack-ng/Makefile
fix issue https://github.com/coolsnowwolf/lede/issues/3855
> aircrack-ng: Update to 1.6

- net/sqm-scripts/Makefile
> sqm-scripts: bump version

- multimedia/ffmpeg/Makefile
> ffmpeg: fix compile error

- net/miniupnpd/files/upnpd.config
> miniupnpd: default enable

- utils/pigz/Makefile
- utils/pigz/patches/001.patch
Signed-off-by: Ken Wong <xinxijishuwyq@gmail.com>
Description:
> pigz: add package

- libs/libuv/Makefile
- libs/libuvc/Makefile
> libuv/libuvc: update to latest

- libs/uw-imap/Makefile
- libs/uw-imap/patches/010-imap-2007f-openssl-1.1.patch
- libs/uw-imap/patches/020-deprecated-openssl.patch
from issue https://github.com/coolsnowwolf/lede/issues/4064
> uw-imap: fix compilation

- net/ddns-scripts/files/update_cloudflare_com_v4.sh
copy from https://github.com/openwrt/packages/blob/master/net/ddns-scripts/files/update_cloudflare_com_v4.sh
Description:
> Fix grep patterns

- devel/gcc/patches/020-disable-check-for-sys-sdt-h.patch
- devel/gcc/patches/970-replace-memcpy-memset.patch
Signed-off-by: W. Michael Petullo <mike@flyn.org>
Maintainer: Christian Beier <cb@shoutrlabs.com>
Compile tested: AArch64 RaspberryPi4B
Run tested: AArch64 RaspberryPi4B
Description:
Upstream patch
> gcc: fix build with 8.3.0

- admin/netdata/Makefile
PKG_VERSION:=1.23.2
Description:
> update netdata to 1.23.2

- utils/docker-ce/Makefile
- utils/docker-ce/files/etc/docker/daemon.json
修复docker-ce按照说明配置后无法启动的[问题](https://github.com/coolsnowwolf/lede/issues/5264)
主要是加了一个配置文件
以及修改了一行Makefile
在自己的软路由上测试通过了
> fix error of 'https://github.com/coolsnowwolf/lede/issues/5264'

- net/shadowsocks-libev/Makefile
shadowsocks-libev:Disable shadowsocks-libev-config select
> shadowsocks-libev:Disable shadowsocks-libev-config select

- net/xtables-addons/Makefile
Maintainer: @jow-
Compile tested: x86_64
Run tested: x86_64
Description:
> xtables-addons: update to 3.13

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v2.2.4

- net/softethervpn/Makefile
> Bump version to 4.34-9745

- net/ddns-scripts/files/update_cloudflare_com_v4.sh
ref: openwrt/packages#12762
docs: https://openwrt.org/docs/guide-user/services/ddns/client#cloudflarecom
> ddns-scripts: Support Bearer Token for Cloudflare

- lang/golang/golang-build.sh
- lang/golang/golang-compiler.mk
- lang/golang/golang-host-build.mk
- lang/golang/golang-package.mk
- lang/golang/golang-values.mk
- lang/golang/golang/Config.in
- lang/golang/golang/Makefile
- lang/golang/golang/files/go-gcc-helper
- lang/golang/golang/patches/001-allow-flags-in-CGO_LDFLAGS-environment-variable-not-in-security-allowlist-GH-42567.patch
V2ray-core V4.33.0 Dependencies to upgrade
> golang : update v1.15.5

- net/xtables-addons/Makefile
> xtables-addons: fix package installation

- admin/htop/Makefile
> Htop : Update V3.0.4

- utils/ttyd/Makefile
- utils/ttyd/files/ttyd.init
- utils/ttyd/patches/100-log-to-syslog.patch
> ttyd : update v1.6.3

- admin/sudo/Makefile
Fixes: CVE-2021-3156 (known as Baron Samedit)
> sudo: update to 1.9.5p2

- utils/containerd/Makefile
- utils/runc/Makefile
> runc: fixed compiler error

- utils/containerd/Makefile
- utils/docker-ce/Makefile
- utils/libnetwork/Makefile
- utils/runc/Makefile
* Needs tests, don't merge it right now.
> docker: fix build with golang 1.16

- admin/sudo/Makefile
- admin/sudo/patches/010-cross-compile-fixes.patch
- admin/sudo/patches/020-no-owner-change.patch
Synchronize official source code
> sudo: update to 1.9.6p1

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to 2.2.13

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v2.2.14

- net/udpxy/Makefile
Description:
Merged with upstream
> Udpxy: update to latest version

- utils/yq/Makefile
> yq: update to 4.9.6

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v2.4.1

- sound/forked-daapd/Makefile
> forked-daapd:fix missing of libopus

- net/strongswan/Makefile
> strongswan: trivial improvement in 'stroke' packaging

- mail/postfix/files/postfix.init
- net/apfree-wifidog/files/wifidogx.init
- net/gnunet/files/gnunet.init
- net/nginx/files/nginx.init
- net/openvswitch/files/openvswitch.init
- net/radicale/files/radicale.init
- net/seafile-server/files/seafile-server.init
- net/simple-adblock/files/simple-adblock.init
- net/tgt/files/tgt.init
- net/travelmate/files/travelmate.init
- net/vpnbypass/files/vpnbypass.init
- net/wifidog/files/wifidog.init
- utils/dockerd/files/dockerd.init
修复部分软件包的“extra_command：not found”提示错误
> packages: use old extra_command wrapper

- lang/php7/Makefile
- lang/php7/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch
> php7: update to 7.4.21

- lang/php8/Makefile
- lang/php8/patches/0025-php-5.4.9-fixheader.patch
- lang/php8/patches/0041-Add-patch-to-remove-build-timestamps-from-generated-.patch
- lang/php8/patches/1004-disable-phar-command.patch
> php8: update to 8.0.8

- net/shadowsocks-libev/Makefile
> shadowsocks-libev:Remove default config selection

- utils/yq/Makefile
> yq: update to 4.11.0

- net/samba4/Makefile
> samba4: update to 4.14.6

- multimedia/ffmpeg/Makefile
> ffmpeg: Update to 4.4

- lang/php7/Makefile
> php7: update to 7.4.22

- libs/spdlog/patches/010-fmt8.patch
> spdlog: fix compilation with fmtlib 8

- net/net-snmp/Makefile
> Update net-snmp to v5.9.1

- multimedia/tvheadend/Config.in
- multimedia/tvheadend/Makefile
- multimedia/tvheadend/files/dvb.hotplug
- multimedia/tvheadend/files/tvheadend.init
- multimedia/tvheadend/patches/001-Makefile.hdhomerun-update-library-to-version-2018081.patch
- multimedia/tvheadend/patches/010-openssl-deprecated.patch
- multimedia/tvheadend/patches/030-gcc10.patch
- multimedia/tvheadend/patches/040-fortify.patch
tvheadend: add patch to update hdhomerun
Description:
> tvheadend: update to 4.2.8

- net/acme/Makefile
>  acme: update to 3.0.1

- net/ddns-scripts/files/update_cloudflare_com_v4.sh
Compile tested: rockchip, nanopi r4s
Run tested: rockchip, nanopi r4s, latest version, tests done
Description:
参考dnspod的域名分离处理
> ddns-scripts: fix cloudflare __HOST and __DOMAIN split

- utils/ntfs-3g/Makefile
> ntfs-3g: bump to 2021.8.22

- net/ariang/Makefile
Signed-off-by: Rosen Penev <rosenp@gmail.com>
x86测试通过
> ariang: update to 1.2.3

- utils/docker/Makefile
- utils/dockerd/Makefile
> docker/dockerd update to 20.10.12

- net/uugamebooster/Makefile
> uugamebooster bump to v2.19.10

- libs/nss/Makefile
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>
> nss: update to 3.76

- libs/nspr/Makefile
Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>
> nspr: update to 4.33

- lang/node/Makefile
- lang/node/patches/v16.x/003-path.patch
- lang/node/patches/v16.x/004-musl_support.patch
- lang/node/patches/v16.x/007-fix_host_build_on_macos.patch
- lang/node/patches/v16.x/010-execvp-arg-list-too-long.patch
- lang/node/patches/v16.x/012-changing-default-npm-settings.patch
- lang/node/patches/v16.x/999-cast_for_mips32.patch
- lang/node/patches/v16.x/999-delete_unnecessary_libraries_for_host_execute.patch
- lang/node/patches/v16.x/999-deps-v8-src-trap-handler-trap-handler.h.patch
- lang/node/patches/v16.x/999-fix_icu_conflict.patch
- lang/node/patches/v16.x/999-localhost-no-addrconfig.patch
- lang/node/patches/v16.x/999-v8_zlib_support.patch
Signed-off-by: Hirokazu MORIKAWA <morikw2@gmail.com>
Maintainer: Hirokazu MORIKAWA @nxhack
Description: add node v16.x and set by default
> node: add v16.x

- net/zerotier/Makefile
- net/zerotier/patches/0001-fix-makefile.patch
- net/zerotier/patches/0002-gcc10.patch
- net/zerotier/patches/0003-add-cerrno-header-for-str-errno.patch
- net/zerotier/patches/0004-fix-compilation-for-arm_cortex-a7-neon.patch
- net/zerotier/patches/0005-auxv.patch
Also refresh patches.
Signed-off-by: Moritz Warning <moritzwarning@web.de>
Maintainer: Moritz Warning
Compile tested: master
Description:
minor bugfixes related to other platforms
> zerotier: update to 1.8.5

- net/uugamebooster/Makefile
Description: uugamebooster bump to v2.21.12
> uugamebooster bump to v2.21.12

- net/nft-qos/files/nft-qos-dynamic.hotplug
- net/nft-qos/files/nft-qos-monitor.hotplug
> nft-qos delete debug log

- net/softethervpn/patches/150-disable-restriction.patch
Description:
@Beginner-Go @badgv
> 150-disable-restriction.patch: fixing line ending

- net/qBittorrent-static/Makefile
> qBittorrent-static: update to 4.4.2_v2.0.6

- utils/tintin/Makefile
Signed-off-by: wzyou <wzyou.goo@gmail.com>
Description:
> tintin: add new package

- net/acme/Makefile
1. add notification and deployment support
2. bump to 3.0.3
> upgrade acme.sh package

- net/zerotier/Makefile
- net/zerotier/patches/0001-fix-makefile.patch
Signed-off-by: JusticeEER <zgfgd3443@protonmail.com>
> zerotier: update to 1.10.0

- net/mosdns/files/config.yaml
> mosdns: Update default config template

- net/softethervpn5/patches/150_remove-restriction.patch
Compile tested: x86_64
Run tested: x86_64
Description:
移除softethervpn5的功能限制
> SoftEther 150_remove-restriction.patch

- utils/rrdtool1/Makefile
Fixed: https://github.com/coolsnowwolf/lede/issues/10193
Fixed: https://github.com/coolsnowwolf/lede/issues/10196
Fixed: https://github.com/coolsnowwolf/lede/issues/10201
> rrdtool1: fix broken download url

- net/qBittorrent-static/Makefile
> qBittorrent-static: update to 4.4.5_v2.0.7

- net/mosdns/Makefile
> mosdns: update to 4.5.2

- net/nginx/Config_ssl.in
- net/nginx/Makefile
Signed-off-by: Jianhui Zhao <zhaojh329@gmail.com>
Maintainer: Thomas Heil
Compile tested: (x86, , master)
Run tested: (x86, , master, tests done)
> nginx: support gzip static mudule

- net/freeradius3/patches/020-fix-mschap-auth.patch
- net/freeradius3/patches/021-add-default-client-and-user-set.patch
username: openwrt password: openwrt
username: user1   password: password
radius secret: testing123
radius client ip-range: 192.168.0.0/16 & 10.0.0.0/8
> freeradius3: fix mschap & add default setting

- net/ddns-scripts/files/update_cloudflare_com_v4.sh
Maintainer: blank
Compile tested: rockchip, nanopi r4s, latest master version
Run tested: rockchip, nanopi r4s, latest master version, tests done
Description:
修正cloudflare查询dns_records时，根域名使用 @.xxx.xxx 无法查询
> ddns-scripts: fix cloudflare dns_records query param while using root domain

- net/zerotier/Makefile
> zerotier: update to 1.10.5

- net/qBittorrent/Makefile
Changelog: https://github.com/qbittorrent/qBittorrent/blob/v4_5_x/Changelog
> qBittorrent: update to 4.5.2

- multimedia/aliyundrive-webdav/Makefile
- multimedia/aliyundrive-webdav/files/aliyundrive-webdav.config
- multimedia/aliyundrive-webdav/files/aliyundrive-webdav.init
> aliyundrive-webdav: update to 2.2.1

- net/uugamebooster/Makefile
> uugamebooster bump to v3.13.4

- net/smartdns/Makefile
Version update.
Maintainer: picmax@gmail.com
Compile tested: QEMU X86_64
Run tested: OpenWrt R23.5.1 / LuCI Master 
Description: Just version update from official source.
> Bump to version 1.2023.42 from 1.2023.41

- net/zerotier/files/etc/init.d/zerotier
1. fix config_path: create and persist
2. fix secret: support identity.secret
3. fix stop_instance: remove existing networks
Maintainer: me / @Beginner-Go 
Compile tested: none (just script)
Run tested: x86-64, ramips-mt7621
Description: fix bug
> zerotier: fix bug

- net/bonding/files/lib/netifd/proto/bonding.sh
- utils/irqbalance/files/irqbalance.config
- utils/irqbalance/files/irqbalance.init
- utils/qemu/Makefile
> qemu io_uring feature and bonding patches

- multimedia/aliyundrive-webdav/Makefile
>  aliyundrive-webdav: Update to 2.3.2 and Build with code

- net/curl/Makefile
https://curl.se/changes.html#8_3_0
> Update curl 8.3.0

- net/unbound/Makefile
- net/unbound/patches/010-configure-uname.patch
> update unbound 1.180

- net/curl/Makefile
> Fox error build

- utils/zstd/Makefile
> fix :ztsd update Makefile

- net/nebula/Makefile
Description:
nebula: update to 1.7.2
> nebula: update to 1.7.2

- libs/libdaq3/Makefile
> libdaq3: update version to 3.0.11

- utils/containerd/Makefile
- utils/docker-compose/Makefile
- utils/docker/Makefile
- utils/dockerd/Makefile
- utils/runc/Makefile
> docker: update all packages bump to 24.0.7

- net/ddns-scripts/files/ddns.init
> 修复重启系统，DDNS 不自动启动问题

- net/strongswan/Makefile
- net/strongswan/files/swanctl.init
- net/strongswan/patches/0900-src-Patch-for-building-with-musl-on-openwrt-taken-ve.patch
- net/strongswan/patches/0901-uci-verbatim-patch-from-openwrt-package-sources.patch
- net/strongswan/patches/0904-gmpdh-Plugin-that-implements-gmp-DH-functions-in-an-.patch
- net/strongswan/patches/0905-undef-wolfssl-RNG.patch
> update strongswan version to 5.9.13

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
Description:
https://curl.se/changes.html#8_5_0
> curl: update to 8.5.0

- net/nebula/Makefile
> nebula: update to 1.8.1

- net/openconnect/Makefile
- net/openconnect/patches/010-libxml212.patch
Remove upstream backport and fix libxml 1.12 compilation
> openconnect: update to 9.12

- net/tailscale/Makefile
- net/tailscale/patches/020-tailscaled_fake_iptables.patch
- net/tailscale/patches/030-default_to_netfilter_off.patch
Maintainer: Jan Pavlinec <jan.pavlinec1@gmail.com>
Compile tested: x86_64, latest master version
Run tested: x86_64, latest master version, tests done
Description:
tailscale: update to 1.44.3
the latest version with iptables support
> tailscale: update to 1.44.3

- net/curl/Makefile
- net/curl/patches/200-no_docs_tests.patch
https://curl.se/changes.html#8_6_0
> curl: update to 8.6.0

- utils/xfsprogs/Makefile
- utils/xfsprogs/patches/120-disable_assert.patch
fix xfsprogs compile issues and update to 6.2.0
> xfsprogs: fix compile issues

- utils/gptfdisk/Makefile
- utils/gptfdisk/patches/010-Use-64bit-time_t-on-linux-as-well.patch
fix gptfdisk compile issues and update to 1.0.9
> gptfdisk: fix compile issues

- net/v2ray-geodata/Makefile
- geoip.dat: update to [202404040040](https://github.com/v2fly/geoip/releases/tag/202404040040)
- dlc.dat: update to [20240404120755](https://github.com/v2fly/domain-list-community/releases/tag/20240404120755)
> v2ray-geodata: update to 202404040040

- net/nps/Makefile
> nps: Update to 0.26.18

- utils/docker-compose/Makefile
> docker-compose: Update to version 2.27.0

- net/tailscale/Makefile
> tailscale: Update to 1.66.1

- net/tailscale/Makefile
> tailscale: Update to 1.66.3

- net/haproxy/Makefile
- net/haproxy/get-latest-patches.sh
> haproxy: update to v3.0.0

- net/uugamebooster/Makefile
> uugamebooster: bump to v6.3.10

- net/acme/Makefile
> acme: update to 3.0.7

- net/transmission/files/transmission.config
- net/transmission/files/transmission.init
> fix: transmission web 404

- net/uugamebooster/Makefile
> uugamebooster: bump to v7.8.0

- net/zerotier/Makefile
- net/zerotier/files/etc/config/zerotier
- net/zerotier/files/etc/init.d/zerotier
- net/zerotier/files/etc/uci-defaults/80-zt-migration
- net/zerotier/patches/0001-fix-miniupnpc-natpmp-include-path.patch
- net/zerotier/patches/0002-remove-PIE-options.patch
- net/zerotier/patches/0003-fix-compilation-for-arm_cortex-a7-neon.patch
- net/zerotier/patches/0004-add-missing-libatomic.patch
- net/zerotier/patches/0005-remove-noexecstack.patch
Compile tested: x86-64
Run tested: x86-64
> zerotier: referesh patches and merge other upstream changes

- net/apcupsd/Makefile
同步上游更新
[coolsnowwolf/lede#13288](https://github.com/coolsnowwolf/lede/issues/13288)
> apcupsd: fix gcc 13 compliation error

- net/rclone/Makefile
- net/rclone/files/rclone.init
> rclone: bump to 1.69.0

- net/chinadns-ng/Makefile
> Update chinadns-ng to 2024.12.22

- net/geoview/Makefile
- net/sing-box/Makefile
> geoview: update to 0.1.6  sing-box: update to 1.11.7

- net/sing-box/Makefile
> sing-box: update to 1.11.8

- net/xray-core/Makefile
> xray-core: update to 25.4.30

- net/sing-box/Makefile
> sing-box: update to 1.11.10

- net/sing-box/Makefile
- net/v2ray-geodata/Makefile
- net/xray-core/Makefile
> sing-box: update to 1.11.13

- net/xray-core/Makefile
> xray-core: update to 25.7.26 
